<template>
  <div>
    <dy-button-group>
      <dy-button type="primary" icon="dy-icon-arrow-left" icon-position="left"
        >上一页</dy-button
      >
      <dy-button type="primary" icon="dy-icon-arrow-right" icon-position="right"
        >下一页</dy-button
      >
    </dy-button-group>
    <dy-button-group>
      <dy-button
        type="primary"
        icon="dy-icon-edit"
        icon-position="left"
      ></dy-button>
      <dy-button
        type="primary"
        icon="dy-icon-share"
        icon-position="right"
      ></dy-button>
      <dy-button
        type="primary"
        icon="dy-icon-setting"
        icon-position="right"
      ></dy-button>
    </dy-button-group>
  </div>
</template>
